src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 155)]
    private $nom;

    #[ORM\Column(type: 'string', length: 155)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 15, nullable: true)]
    private $telephone;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $adresse;

    #[ORM\Column(type: 'string', length: 5, nullable: true)]
    private $code_postal;

    #[ORM\Column(type: 'string', length: 1, nullable: true)]
    private $civilite;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Contact::class)]
    private $contacts;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commande::class)]
    private $commandes;

    public function __construct()
    {
        $this->contacts = new ArrayCollection();
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(?string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setUser($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getUser() === $this) {
                $contact->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;


use App\Classes\Panier;
use App\Form\ConfirmationLivraisonType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PanierController extends AbstractController
{
    #[Route('/panier', name: 'panier')]
    public function index(Panier $panier): Response
    {
       // $panier->addProduitPanier(2);
        return $this->render('panier/index.html.twig', [
           'panier' =>$panier->getDetailPanier(),
           'total_panier' => $panier->getTotalPanier()
        ]);
    }

    #[Route('/delete-panier', name: 'delete_panier')]
    public function delete(Panier $panier): Response
    {
        $panier->deletePanier();
        return $this->redirectToRoute('panier');
    }

    #[Route('/add-panier/{id}', name: 'add_panier')]
    public function add(Panier $panier, $id): Response
    {
        $panier-> addProduitPanier($id);
        return $this->redirectToRoute('panier');
    }

    #[Route('/delete-quantity-panier/{id}', name: 'delete_quantity_panier')]
    public function deleteQuantityProd(Panier $panier, $id): Response
    {
        $panier->deleteQuantityProd($id);
        return $this->redirectToRoute('panier');
    }

    #[Route('/confirmer-panier', name:'confirme_panier')]
    public function confirmePanier(Request $request, EntityManagerInterface $manager, Panier $panier)
    {
        //je récupére l utilisateur connecté
        $user = $this->getUser();
         // si notre client n'a pas renseigné un nom ou une adresse ou un code postal
        // on le renvoie vers un formulaire pour compléter les données 
        if(!$user->getNom() || !$user->getAdresse() || !$user->getCodePostal())
        {
            $form = $this->createForm(ConfirmationLivraisonType::class, $user);
            $form->handleRequest($request);    

            if($form->isSubmitted() && $form->isValid())
            {
                $manager->persist($user);
                $manager->flush();
                return $this->redirectToRoute('confirme_panier');
            }
            return $this->render('panier/confirmation_panier.html.twig',[
                'form' => $form->createView()
    
            ]);

        }
        //si l utilisateur a enregistrer son adresse de livraison je lui retourne la vue du panier
        //sinon je lui envoie un formulaire 
        return $this->render('panier/recap_panier.html.twig',[
            'panier'=>$panier->getDetailPanier(),
            'total_panier'=>$panier->getTotalPanier()
    
        ]);
        
    }


}

templates/panier/confirmation_panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <div class="container">
    {{form_start(form)}}
        <input type="submit" value="ok">
    {{form_end(form)}}

    
    </div>
{% endblock %}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PanierController!{% endblock %}

{% block body %}
{% if app.user %}
			<h1>votre panier
				{{app.user.prenom}}
			</h1>
		{% endif %}
 <div class = 'container'>
 <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
 <table class="table">
  <thead>
    <tr>      
      <th scope="col">produit</th>      
      <th scope="col">quantité</th>      
      <th >total</th>
      <th >action</th>
    </tr>
  </thead>
  <tbody>

  {% for item in panier %}
	<tr>
		<td scope="row">{{item['produit'].getNom()}}</td>
		<td scope="row">{{item['quantite']}}</td> 
		<td scope="row">{{item['total']}}€</td> 
		<td><a href="{{ path('delete_quantity_panier',{'id' : item['produit'].getId()}) }}"><i class="fa fa-minus-square" aria-hidden="true"></i></a>
		<a href="{{ path('add_panier', {'id' : item ['produit'].getId()}) }}"><i class="fa fa-plus-square" aria-hidden="true"></i></a></td>
	</tr>
  {% endfor %}
   
</table>
<h3>Le total de votre panier : {{total_panier}}€  </h3>

<a href="{{ path('delete_panier') }}">supprimer panier</a>
<a href="{{ path('confirme_panier')}}">confirmation panier</a>
<a href="{{ path('categorie_catalogue')}}">retour aux menus</a>

</div> 

{% endblock %}

templates/panier/recap_panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PanierController!{% endblock %}

{% block body %}

 <div class = 'container'>

 <h3>Votre recapitulatif de commande avant le réglement</h3>
 <hr>

 <div class="row">
    <div class="col-6">
    <h5>Information client :</h5>
    <p>Nom  : {{app.user.nom }}</p>
    <p>Prenom : {{ app.user.prenom}}</p>
    <p>Téléphone : {{ app.user.telephone}}</p>
    <p>Votre adrresse de livraison : {{ app.user.adresse ~ ' '~ app.user.codePostal}}</p>
    <hr>

    <h3>Commande :</h3>
    
</div>

 <table class="table">
  <thead>
    <tr>
      
      <th scope="col">produit</th>      
      <th scope="col">quantité</th>      
      <th scope="col">total</th>
      
    </tr>
  </thead>
  <tbody>

  {% for item in panier %}
	<tr>
		<td scope="row">{{item['produit'].getNom()}}</td>
		<td scope="row">{{item['quantite']}}</td> 
		<td scope="row">{{item['total']}}€</td> 		
	</tr>
  {% endfor %}
 
</table>
 
<a href="#">Modifier l'addresse</a>
<a href="{{path('app_achat')}}">Passer à l'achat</a>
<a href="{{path('delete_panier')}}">Annuler Commande</a>

</div> 

{% endblock %}